### PR TITLE
#37405551-docs(): Api design documentation

### LINKED ISSUE #6: Rest API design
- Come out with endpoints for the project
- Use the open API v3.0.0 specification
- Make use of platforms that can export the API docs to pdf, Html, yuml or JSON
- You can check out the following platforms ​[swagger](https://editor.swagger.io/),​ [open-api gu](https://mermade.github.io/openapi-gui/)
- Make use of schemas designed in ​ #3 
- In case of doubts please post in the group

### PR DESCRIPTION
**Pull request by tanerochris**
## Description
OpenAPI 3.0 design
Yaml and JSON files

fixes #6

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mernxl** [comment]
Please can we see a hosted version of this??

**Comment by tanerochris** [comment]
> Please can we see a hosted version of this??

https://app.swaggerhub.com/apis/tanerochris/qpi/0.1-oas3

**Comment by cliffordten** [comment]
Are the endpoints complete @tanerochris ? I don't see organisations and comment endpoints?

**Comment by tanerochris** [comment]
> Are the endpoints complete @tanerochris ? I don't see organisations and comment endpoints?

not, yet created the endpoints we needed to start with. When we done with that will add the other endpoints.

**Comment by mernxl** [comment]
hey, why can't you model the endpoints like #16, so we don't have to redo the authentication, also it hase more features.

**Comment by tanerochris** [comment]
> hey, why can't you model the endpoints like #16, so we don't have to redo the authentication, also it has more features.

Renaming the endpoints to that designed is not a problem, however what I will change is the user password schema to match #16

**Comment by mernxl** [comment]
user password schema. ??
that isn't public, its not populated like ever.

**Comment by tanerochris** [comment]
> user password schema. ??
> that isn't public, its not populated like ever.

it's not public but is returned in response on user creation. Well I think that is the case, currently can't reproduce that, pulled latest updates on #16  and can no longer signup

**Comment by mernxl** [comment]
Actually its because you pass a null value for password.

Also the password is never going to show up in public, if you notices, when populated the password, when i want to set session, i get fresh record from the db

**Comment by tanerochris** [comment]
> Actually its because you pass a null value for password.
> 
> Also the password is never going to show up in public, if you notices, when populated the password, when i want to set session, i get fresh record from the db

I pass a password, trying to signup but that's the error I get. About the password, the schema is not just for public purposes, I combined the modifications you did on #3 with @dherve19  for the overll mongodb schema not just for the api endpoint purposes. I think I requested somewhere that you follow the schemas when creating the mongo schemas. That's why you see password.

**Comment by mernxl** [comment]
> Actually its because you pass a null value for password.
> 

Was speaking out of context there, its a reply to your comment on #16 about null password.

**Review by mernxl — APPROVED** [review]
Ok, Lets move on.

**Review by cliffordten — APPROVED** [review]
Sorry, Thought i already gave my review

**Review by KaiserPhemi — APPROVED** [review]

**Pull request merged**
